### ISSUE TITLE
Stuck at waiting for tagbox to be ready.

### ISSUE THREAD

**Issue by nerdprogrammergm** [machinebox/visualsearch#1]
Hello there,
I am using tagbox with visualsearch. My tagbox is successful setup in docker and working fine. I am trying to setup the visualsearch on my system. I am facing the problem and it is when I run "make run", the process get stuck at "Wating for Tagbox to be ready...", my tagbox is already running and I can access it on browser. After sometime the tagbox shutdown and visualsearch still stuck at the same position. 
Please help me out!

This is the tagbox docker output:
	Visit the console to see what this box can do:
	http://localhost:8080

	If you have any questions or feedback, get in touch:
	https://machinebox.io/contact

	Please consider buying a subscription:
	https://machinebox.io/#pricing

	Report bugs and issues:
	https://github.com/machinebox/issues

	Tell us what you build via @machineboxio

	Minimum recommended: 6GB RAM
	
2017/10/10 12:26:33 [CRITICAL] command exited during start up
2017/10/10 12:26:33 command exited during start up

**Comment by dahernan** [comment]
It seems that Tagbox is not running properly.
```
2017/10/10 12:26:33 [CRITICAL] command exited during start up
```
The most common cause for that is lack of memory make sure you have 6BG of RAM assigned to docker, like in this screenshot
<img width="381" alt="screen shot 2017-09-30 at 21 11 15" src="https://user-images.githubusercontent.com/615811/31389967-e0991fac-add2-11e7-8405-654c7b6a6875.png">

If you check the console on http://localhost:8080 you should see something like this (with box ready on green):
<img width="1400" alt="screen shot 2017-10-10 at 15 54 03" src="https://user-images.githubusercontent.com/615811/31390125-550cf228-add3-11e7-938f-c8319e1e2342.png">

Let me know if that works.

**Comment by nerdprogrammergm** [comment]
Thanks,it worked! 👯‍♂️
