### ISSUE TITLE
Still facing problem running visualsearch :(

### ISSUE THREAD

**Issue by nerdprogrammergm** [machinebox/visualsearch#2]
Hello there,
As per your instruction, I did exactly same and everything was working fine. But today when I started my mac and tried running the visual search again ,when I run the command "make run", I am getting this error, please help me out by guiding me.
 Thanks in advance!
Error is "decoding response: json: cannot unmarshal number into Go value of type struct { Success bool; Error string }
make: *** [run] Error 1"

**Comment by dahernan** [comment]
Can you provide more details, about what you are doing, I have no intuition about this problem

**Comment by dahernan** [comment]
I assume that it is been resolved, feel free to reopen
